config/routes.rb
Rails.application.routes.draw do
  root "simulations#new"

  post "create_simulation", to: "simulations#create"
  get "/simulations/:id", to: "simulations#show", as: 'simulation'
  post 'send_email', to: "simulations#send_email"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/professions/base.rb
module Professions
  class Base

    def deductible_formula
      "medium"
    end

    def coverage_ceiling_formula
      "medium"
    end

    def cover
      raise NotImplementedError, "Please implement in a descendant."
    end

  end
end

app/models/professions/doctors.rb
module Professions
  class Doctors < Base
    def deductible_formula
      "small"
    end

    def coverage_ceiling_formula
      "large"
    end

    def cover
      "legalExpenses"
    end
  end
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  validates :email, :phone_number, :first_name, :last_name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController

  def new
    @simulation = Simulation.new
  end

  def create
    interactor = ::Simulations::Create.new(params: simulation_params.to_h)
    simulation = interactor.call
    if simulation.valid?
      redirect_to :action => "show", :id => simulation.id
    else
      render :new
    end
  end

  def show
    @simulation = Simulation.find(params[:id])
    interactor = ::CoverPropositions::Create.new(simulation: @simulation)
    @result = interactor.call
  end

  def send_email
    simulation = Simulation.find(params[:simulation_id])
    SimulationMailer.with(simulation: simulation, domain_name: request.host).send_simulation_email.deliver_now
  end

  private

  def simulation_params
    params.require(:simulation).permit(:profession,
                                       :annual_revenue,
                                       :enterprise_number,
                                       :legal_name,
                                       :natural_person,
                                       :email,
                                       :phone_number,
                                       :address,
                                       :first_name,
                                       :last_name)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yago</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simulations/new.html.erb
<div>
  <%= form_with model: @simulation, url: create_simulation_path do |f| %>

    <div class="field">
      <%= f.label :First_Name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :Last_Name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :Phone_Number %><br>
      <%= f.telephone_field :phone_number %>
    </div>

    <div class="field">
      <%= f.label :Address %><br>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :Profession %><br>
      <%= f.select :profession, options_for_select(["Doctors"]) %>
    </div>

    <div class="field">
      <%= f.label :Annual_Revenue %><br>
      <%= f.number_field :annual_revenue %>
    </div>

    <div class="field">
      <%= f.label :Enterprise_number %><br>
      <%= f.text_field :enterprise_number %>
    </div>

    <div class="field">
      <%= f.label :Company_name %><br>
      <%= f.text_field :legal_name %>
    </div>

    <div class="field">
      <%= f.label :natural_person, "Natural Person ?" %>
      <%= f.radio_button :natural_person, true %>
      <%= f.label :natural_person, "Yes" %>
      <%= f.radio_button :natural_person, false %>
      <%= f.label :natural_person, "No" %>
    </div>

    <div class="actions">
      <%= f.submit "save"%>
    </div>
  <% end %>
</div>

app/views/simulations/show.html.erb
<h1>Hello</h1>

<h3>Voici les couvertures disponibles :</h3>
<% @result[:cover_premiums].each do |key, value|  %>
  <p><%= key %> : <%= value %></p>
<% end %>
<div>
  <h3>Nous vous conseillons</h3>
  <%= @result[:cover_advice] %>
  <h3>Avec</h3>
  <p>Coverage Ceiling : <%= @result[:coverage_ceiling] %></p>
  <p>Deductible : <%= @result[:deductible] %></p>
</div>


<div>
  <%= button_to 'Send', send_email_path(simulation_id: @simulation.id), method: 'post' %>
</div>